<?php
/*
    File: gl-body-elem.php
    Desc: Grid Layout <body> element for grid layout Tempate
    Date: 2023-04-17
    Auth: sumkittehz.codes
*/

$phpmodules = array(
    "gl-item-head.php",
    "gl-item-menu.php",
    "gl-item-main.php",
    "gl-item-foot.php",
);
/* 
   open the body element 
   TODO: the HTML generated by this podule should be accumulated 
         into an output string - This echo statement should be replaced 
         by e.g. '$html_output_string .= <<<' - this means that the output string
         must be declared at the top of the module, assignments to the output string
         using '.=' should replace all echo statements.
*/
echo <<<'EOE'
<body>
  <details>
    <summary><span class="info">#file-info</span></summary>
    <pre class="file-info">
      File: grid-layout.10.php
      Desc: Responsive Grid Layout Template Example
      Date: 2023-04-17
      Auth: <a href="https://sumkittehz.codes/">sumkittehz.codes</a>
    </pre>
  </details>
EOE;

/* open grid-container -- this is the element that has the grid map 
   in CSS (selector .gird-container  -- */
echo('<div class="grid-container">'."\n");
/* require each of the PHP modules required by the template */
foreach($phpmodules as $fn) { require( $fn ); }
echo( "  </div><!-- close DIV class grid-container -->\n" );  

/*  Create source file listings */
$srcfilelst = array( "grid-layout.10.css","grid-layout.10.php" );

foreach ( array( "grid-layout.10.css","grid-layout.10.php" ) as $fn) {
     echo '<details><summary><span class="info">'.$fn.'</summary>';
     echo '<pre class="filelisting">Filename:  <a target="_blank" href="'.$fn.'">'.$fn.'</a>'."\n<hr/>\n";
     highlight_file($fn);
     echo "<hr>";
     echo '<span>end of file '.$fn."</span></pre>\n";
     echo "</details>";
   }
echo( "  </body>\n" );
?>
